knpu_oauth2_client:
    clients:
        strava:
            type: generic
            provider_class: App\OAuth\StravaOAuthProvider
            client_id: '%app.strava.client_id%'
            client_secret: '%app.strava.client_secret%'
            redirect_route: connect_strava_check
            redirect_params: {}
